{% set name = "opentelemetry-exporter-jaeger-thrift" %}
{% set version = "1.21.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz

  sha256: 41119bc7e5602cec83dd7d7060f061ecbc91de231272e8f515b07ef9a4b6e41c
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - hatchling
  run:
    - python >=3.6
    - thrift >=0.10.0
    - opentelemetry-api ~=1.3
    - opentelemetry-sdk ~=1.11
test:
  imports:
    - opentelemetry
  commands:
    - pip check
  requires:
    - pip
about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-jaeger-thrift

  summary: Jaeger Thrift Exporter for OpenTelemetry
  license: Apache-2.0

  license_file: LICENSE
extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
