{% set name = "opentelemetry-exporter-jaeger-thrift" %}
{% set version = "1.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_jaeger_thrift-{{ version }}.tar.gz
  sha256: 41119bc7e5602cec83dd7d7060f061ecbc91de231272e8f515b07ef9a4b6e41c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - thrift >=0.10.0
    - opentelemetry-api >=1.3,<2.0
    - opentelemetry-sdk >=1.11,<2.0
test:
  imports:
    - opentelemetry
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-jaeger-thrift

  summary: Jaeger Thrift Exporter for OpenTelemetry
  license: Apache-2.0

  license_file: LICENSE
extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
